### PR TITLE
Fix variable name conflict with Compass v0.13.x

### PR DESCRIPTION
**Pull request by roborn**
When using box-shadow() from Compass v0.13.x, the grid-span() stops working because of a naming conflict the set-arglist-default function: it also uses the $output variable name (see: https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/css3/_shared.scss#L261).

I suggest to change the $output variable to $output-style

### CODE REVIEW

**Comment by scottkellum** [comment]
Looks good to me. Hopefully none of our users are too locked into using `$output`. My reservations are that this is a breaking change for many Singularity users.

**Comment by Snugug** [comment]
I want to dig into this further. The fact that `$output` is a Compass globally scoped variable concerns me, may want to suggest the change in Compass

**Comment by scottkellum** [comment]
I’m leaning towards namspacing it better on our end, well, for Compass as well. `$output` is pretty generic and even if it doesn’t conflict with Compass it may conflict with other plugins in the future.

**Comment by Snugug** [comment]
I agree we need to do something about it, but I don't want to go changing it everywhere until we figure out a good way to namespace.

Considering Compass 0.13 isn't out yet and we don't officially support it yet, I'm of the opinion we hold off on this and work on deprecation when we can use the Map data type to properly namespace everything. Then we can officially support Sass 3.3 _and_ Compass 0.13 while providing only a single deprecation path.

**Comment by scottkellum** [comment]
Agreed

**Comment by Snugug** [comment]
Resolved in #157  (which will become v1.2.0 of Singularity)

**Pull request closed without merging**
