### PR TITLE
Add second color to background grid

### PR DESCRIPTION
**Pull request by robwierzbowski**
I'm making a grid with padding but no gutters, which messes with my use of the awesome `background-grid()` mixin. 

To fix this I revised `grid-gradient-stop()` to use the same logic no matter which column it's on, and then added an optional `$color2` to `background-grid()`.
- If you don't specify a `$color2`, nothing changes. 
- If you set `$color2`, odd columns are `$color` and even columns are `$color2`.
- If you don't specify a `$color2` **and** you have gutters set to 0, `$color2` is automatically set to `$color` but with 1/2 the opacity.

### CODE REVIEW

**Comment by robwierzbowski** [comment]
Hmm. `$color2` is kind of a shitty variable name.

**Comment by Snugug** [comment]
How about $alternate-color

**Comment by robwierzbowski** [comment]
Little bugfix there. `alt-color` or `odd-color`, whatever you think.

**Comment by robwierzbowski** [comment]
How about stripe-color?

**Comment by Snugug** [comment]
Meh, they're both "stripes". It's really the alternate color, and I'd really almost prefer it to be built off of the main color

**Comment by robwierzbowski** [comment]
I considered that at first, and I think you're right. No reason to add choice and complexity.

What do you think: stripes always, only when gutters are 0, or when gutters are below a certain threshold? I've noticed when gutters are really thin some of them will disappear on me.

**Comment by Snugug** [comment]
Below a certain threshold. The background grid, while pretty, is a pretty poor indicator of your actual grid, so a threshold works fine for me.

**Comment by robwierzbowski** [comment]
I think it's working well now.

**Pull request merged**
