### PR TITLE
add rtl support

### PR DESCRIPTION
**Pull request by codingdesigner**
I'm working on my rtl responsive site, and this seems like the simplest solution. It's common, but not universal, practice to set a dir=rtl attribute on the `<html>` element, so this will create  an rtl option that lives alongside the ltr grid. 

You can set the `$dir` to 'ltr', 'rtl', or 'both'. (defaults to ltr) If you choose both the direction switch will be added. Otherwise the floats and margins are just set up for your layout direction.

### CODE REVIEW

**Comment by Snugug** [comment]
So I'm going to test this, and I'm finding Singularity totally frickin busted. It's not pulling in my columns  for starters. I'm going to go investigate.

UPDATE:

Got it working, all looks good. My only concern is that attribute selectors don't work in IE6 and the largest market for RTL, China, is a mostly IE6 nation. While exceedingly clever, thoughts on changing it from attr selector to class, or give users the option to choose?

**Comment by codingdesigner** [comment]
Hmmm. I'll double check it as well. There might be an issue in my transferring it from my project.

**Comment by codingdesigner** [comment]
I got my tests working too, hooray!

I also made the rtl selector configurable.

**Comment by codingdesigner** [comment]
@scottkellum , @Snugug any thoughts on this. It's working well for me.

**Comment by Snugug** [comment]
Like I said, I got it working, I like it. I think something's wrong with my repo so after this gets merged in I'm going to blow away and repull

**Comment by lameei** [comment]
Would you please give me a detailed instruction on changing the grid direction?

**Comment by lolmaus** [comment]
The information is available at the wiki: https://github.com/Team-Sass/Singularity/wiki/Output-Options#grid-direction

For further support, please use [StackOverflow](http://stackoverflow.com/questions/tagged/singularitygs) as outlined in [Singularity support guidelines](https://github.com/Team-Sass/Singularity#getting-help-with-singularity).

**Pull request merged**
